### ISSUE TITLE
Issue within the geo_selector starting to investigate

### ISSUE THREAD

**Issue by v2lrf** [hopsoft/stimulus_reflex_expo#41]
* What was I trying to do?
I'm trying to make the app running locally and try to deal with Geo_selector view

* setup 
All set up done as describe inside the Readme, The app is running locally. 

Does anyone have issue to use Geo_selector locally ? 

I was just so curious to try it tonight and to see how it's running behind the scene. 
Here the issue

I can select the ```@region``` and the region stay displayed
I can select the  ```@subregion``` but the form closed it self just after having clicked on the @subregion. 

So i never see the @country select form. I just start to investigate that and I was wondering if it'q a local issue or if it's a well know issue

**Comment by RolandStuder** [comment]
The expo expects to have redis running as cache_store. This fails silently.

So even if you have enabled the dev cache with `rails dev:cache` it will not work unless there is a redis instance running and reachable under `ENV["REDIS_URL"]`

So the geo_selector will not work because sessions are not persisted across reflexes or requests.

So try to install redis, run it, set the REDIS_URL and see if it works now.

**Comment by leastbad** [comment]
@v2lrf did @RolandStuder's solution work for you?

**Comment by andrewmcodes** [comment]
@leastbad seems like a yes based on the reaction. 

Closing this. Feel free to reopen if needed.
